version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'signicat'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'